name: todo_yandex
description: TODO list(Yandex project).

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_serializable: ^6.3.1
  json_annotation: ^4.5.0
  http: ^0.13.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  flutter_svg: ^1.1.1+1
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  platform_device_id: ^1.0.1
  flutter_riverpod: ^1.0.4
  flutter_launcher_icons: ^0.10.0
  firebase_remote_config: ^2.0.15
  firebase_analytics: ^9.3.2
  freezed_annotation: ^2.1.0
  appmetrica_plugin: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
